# Generated by Django 4.2.17 on 2024-12-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='person',
            new_name='person_one',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='conversation_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='person',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='dementia.person'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='dementia.person'),
        ),
    ]
