# Generated by Django 4.2.17 on 2025-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0003_person_upcoming_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='people',
            field=models.ManyToManyField(blank=True, to='dementia.person'),
        ),
    ]
